version: 0.2
phases:
  install:
    commands:
      - echo install phases
      - echo NODE_ENV- "${NODE_ENV}"
      - echo BRANCH-  "${BRANCH}"

  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      # - npm run build-"${NODE_ENV}"
      # Run test cases only if codebuild environment is configured to run them
      - if [ "${RUN_TESTS}" = "True" ]; then npm run test; fi
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'
  # discard-paths: yes
  base-directory: 'dist/build'
  