name: Danger JS
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install packages
      run: npm i
    - name: Run coverage
      run: npm run coverage
    - name: Danger
      run: npm run runDangerTest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}