name: Danger JS
on: [pull_request]
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install packages
      run: npm i
    # - name: Run coverage
    #   run: npm run coverage
    # - name: Merge coverage report
    #   run: npm run merge
    - name: Danger
      run: npm run runDangerGit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./package.json
    - name: Echo package.json
      run: echo "hahahah ${{ steps.package.outputs.content }}"